In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
bcancer = pd.read_csv('./data.csv')

In [4]:
bcancer.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perimeter_worst  \
0           ...                    25.38          17.33           184.60   
1           ...                    24.99          23.41           158.80   
2           ...                    23.57          25.53           152.50   
3           ...                    14.91          26.50            98.87   
4           ...                    22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
bcancer.shape

(569, 32)

In [6]:
bcancer = bcancer.drop(['id'],axis=1)

In [7]:
bcancer['diagnosis'].replace(['M','B'],['Malignant','Benign'],inplace=True)

In [8]:
bcancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non-null float64
concave points_se          569 n

In [9]:
X = bcancer.iloc[:,1:]
y = bcancer.iloc[:,0]

In [10]:
from sklearn import cross_validation
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

C:\Users\avinash\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3, random_state=0)
rmf_classifier = rmf.fit(X_train,y_train)

C:\Users\avinash\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [13]:
rf_y_test = rmf_classifier.predict(X_test)
rf_y_test

array(['Malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Malignant',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Be

In [14]:
from sklearn.metrics import confusion_matrix
rf_cm_test = confusion_matrix(y_test,rf_y_test)
rf_cm_test

array([[74,  3],
       [ 7, 30]], dtype=int64)

In [15]:
rf_y_train = rmf_classifier.predict(X_train)
rf_y_train

array(['Malignant', 'Malignant', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Malignant', 'Malignant', 'Malignant', 'Malignant',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Malignant', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 

In [16]:
rf_cm_train = confusion_matrix(y_train,rf_y_train)
rf_cm_train

array([[275,   5],
       [  7, 168]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score
rf_acc_test = accuracy_score(y_test, rf_y_test)
rf_acc_test

0.9122807017543859

In [18]:
rf_acc_train = accuracy_score(y_train, rf_y_train)
rf_acc_train

0.9736263736263736

In [19]:
from sklearn.metrics import precision_score
rf_precision_test = precision_score(y_test,rf_y_test,average="weighted")
print(rf_precision_test)
rf_precision_train = precision_score(y_train,rf_y_train,average="weighted")
print(rf_precision_train)

0.9121231811290289
0.9736084437843139


In [20]:
from sklearn.metrics import recall_score
rf_recall_test = recall_score(y_test,rf_y_test,average="weighted")
print(rf_recall_test)
rf_recall_train = recall_score(y_train,rf_y_train,average="weighted")
print(rf_recall_train)

0.9122807017543859
0.9736263736263736


In [21]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
seed = 7
num_trees = 10
kfold = model_selection.KFold(n_splits=10,random_state=seed)

In [22]:
result = model_selection.cross_val_score(rmf_classifier,X_train,y_train,cv = kfold)

In [21]:
result

array([0.91304348, 0.86956522, 0.95652174, 0.95652174, 0.97826087,
       0.93333333, 0.95555556, 0.93333333, 0.91111111, 0.95555556])

In [22]:
result.mean()

0.936280193236715

# ADA BOOST - ADAPTIVE BOOSTING CLASSIFIER

In [23]:
from sklearn.ensemble import AdaBoostClassifier

In [24]:
num_trees = 30
model = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)

In [25]:
ada = model.fit(X_train,y_train)
ada

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=30, random_state=7)

In [26]:
y_pred = ada.predict(X_test)
y_pred

array(['Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Benign', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Malignant', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Benign', 'Malignant',
       'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Benign', 'Malignant', 'Benign', 'Malignant', 'Benign',
       'Malignant', 'Benign', 'Malignant', 'Benign', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Malignant', 'Benign', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Malignant', 'Malignant',
       'Malignant', 'Benign', 'Benign', 'Benign', 'Malignant',
       'Malignant', 'Malignant', 'Ben

In [27]:
ada_train = model.predict(X_train)

In [28]:
from sklearn.metrics import confusion_matrix
ada_cm_train = confusion_matrix(y_train,ada_train)
ada_cm_train

array([[274,   0],
       [  0, 181]], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score
ada_acc_test = accuracy_score(y_test,y_pred)
ada_acc_test

1.0

In [30]:
from sklearn.metrics import accuracy_score
ada_acc_train = accuracy_score(y_train,ada_train)
ada_acc_train

1.0

In [58]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10,random_state=seed)
results = model_selection.cross_val_score(model,X_train,y_train,cv=kfold,scoring='accuracy')

In [59]:
type(kfold)

sklearn.model_selection._split.KFold

In [60]:
results.mean()

0.9626570048309178

##########################

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)

In [46]:
model_knn = knn.fit(X_train,y_train)

In [47]:
model_knn.score(X_train,y_train)

0.945054945054945

In [48]:
model_knn.score(X_test,y_test)

0.9298245614035088

In [54]:
y_pred = model_knn.predict(X_train)

In [56]:
accuracy_score(y_pred,y_train)

0.945054945054945